version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
        #install:
        #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
        #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
        #runtime-versions:
        # name: version
        # name: version
        #commands:
        # - command
        # - command
        #pre_build:
        #commands:
        # - command
        # - command
    build:
        commands:
            - echo We are trying to build this thing..
            - npm install yarn --global
            - yarn install --prod --pure-lockfile
            - echo Well, we are the end here.
            # - command
        #post_build:
        #commands:
        # - command
        # - command
#reports:
#report-name-or-arn:
#files:
# - location
# - location
#base-directory: location
#discard-paths: yes
#file-format: JunitXml | CucumberJson
#files:
# - location
# - location
#name: $(date +%Y-%m-%d)
#discard-paths: yes
#base-directory: location
#cache:
#paths:
# - paths
