service: trality-landingpage

provider:
    name: aws
    runtime: nodejs8.10
    region: ${env:APP_REGION}
    stage: ${env:APP_STAGE}
    profile: ${opt:profile, 'default'}
    apiName: ${self:provider.stage}-${self:service}
    stackName: ${self:provider.stage}-${self:service}

plugins:
    - serverless-dotenv-plugin
    - serverless-offline

functions:
    server:
        handler: index.server
        events:
            - http: ANY /
            - http: ANY /{proxy+}
