name: Web Live Release

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  always-auth: true
                  registry-url: https://npm.pkg.github.com
                  scope: '@trality'
            - name: Install web dependencies
              run: yarn install --prod --pure-lockfile
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
            - name: Web build
              run: yarn build:prod
              env:
                  CI: true
            - name: Let lambda know change of live sha
              run: echo ${GITHUB_SHA}
              env:
                  GATSBY_LAMBDA_TOKEN_DEV: ${{secrets.GATSBY_LAMBDA_TOKEN_DEV}}
                  CI: true
